### ISSUE TITLE
13 promax 15.4.1 Sileo doesn't seem to connect to the Internet

### ISSUE THREAD

**Issue by dixtdf** [iarchiveml/Fugu15#2]

**Comment by dixtdf** [comment]
![74438DBB-C282-48E5-A3F3-1BFC7DB46278](https://user-images.githubusercontent.com/106577535/211816152-9d6b21af-4f46-48c0-8d3c-dd4f9c68e4f6.png)

**Comment by iarchiveml** [comment]
This can happen from time to time, close and reopen Sileo.
