### ISSUE TITLE
iOS 15.4.1 - 13 pro max - Wi-Fi disabled and still error jailbreak

### ISSUE THREAD

**Issue by SametChan** [iarchiveml/Fugu15#3]
I tried to disable wifi and network data and happened this error

I tried to uninstall and then reinstall and still the same issue

iOS version: 15.4.1
iPhone Model: 13 Pro max

Screenshot example here,
![0C3C8A12-E787-4DEC-AC1E-A20D7AD96D12](https://user-images.githubusercontent.com/16865563/214056675-ad9a23ea-c571-48a3-99bf-ed73f7b30e07.png)
![F8B75D45-8C33-497F-8A1B-748D44B17973](https://user-images.githubusercontent.com/16865563/214056686-2d5a766c-bf42-4f22-b38f-1919acf5b687.png)

**Comment by iarchiveml** [comment]
Did you install by sideloading? You need to install with trollstore

**Comment by SametChan** [comment]
> Did you install by sideloading? You need to install with trollstore

Yes, I've installed that at Sideloadly. Okay, I will install with trollstore and let you know later.

**Comment by SametChan** [comment]
> Did you install by sideloading? You need to install with trollstore

**Updated**, works well, but still an issue, I've typed the command line: `uicache -r` and error: Command `uicache` not recognized!

Screenshot example here,
![A0AD84E1-BA86-4921-890F-7F4EBF813683](https://user-images.githubusercontent.com/16865563/214099761-e01429a5-0d7b-491a-a62d-788bb6835f7b.png)

**Comment by iarchiveml** [comment]
It's a known error and it's not critical so it probably won't be fixed for a while, I'm unsure why uicache doesn't work but you can use trollstore or command line to run it.
