### ISSUE TITLE
version number of precompiled ipa?

### ISSUE THREAD

**Issue by mio-19** [iarchiveml/Fugu15#5]
I filled out the form and got the ipa. But I can't find any version number information about it.
Is it [v0.0.9](https://github.com/iarchiveml/Fugu15/releases/tag/v0.0.9) or [v0.1](https://github.com/iarchiveml/Fugu15/releases/tag/v0.1)?

**Comment by iarchiveml** [comment]
when filling out the form, you will always receive the latest version. in this case it's version 0.1
