### ISSUE TITLE
[unrelated to code] You need to stop

### ISSUE THREAD

**Issue by Ijustplaymc** [iarchiveml/Fugu15#6]
Just provide the precompiled ipa files already. Dont pull some BS where you need to "take a test" to get them. Anyone can just google them. It is extremely annoying and unnecessary. There is little point, if you want to stop inexperienced people from using this simply add a disclaimer that this is a developer tool. 

Just stop, people who do want to develop for this dont have time for this.

**Comment by iarchiveml** [comment]
No.

**Comment by iarchiveml** [comment]
Sounds like you failed the test, skill issue.
