### ISSUE TITLE
Still no receive from IPA

### ISSUE THREAD

**Issue by SametChan** [iarchiveml/Fugu15#7]
I've been waiting for more than 8 days and still haven't received any from IPA, I've submitted the google forms all of Q were answered and corrected.

**Comment by iarchiveml** [comment]
Check your spam folder, if there is nothing then you got something incorrect.

**Comment by tsy19900929** [comment]
same as me, and no mail in spam folder. my email [fqlcz1990@gmail.com](mailto:fqlcz1990@gmail.com)
![image](https://user-images.githubusercontent.com/24546045/219909859-f094a827-781a-4050-a7c0-4c4039dc7822.png)
![image](https://user-images.githubusercontent.com/24546045/219909867-c11581b5-036b-4be8-a3da-81aed42695bf.png)
